[package]
name = "projecteuler_solving_problems"
version = "0.1.0"
authors = ["VMM <vladimirov.m.m@alex-its.uz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint="*"